services:
  web:
    build:
      context: ..
      dockerfile: docker/flask.dockerfile
    ports:
      - "2808:2808"
    container_name: flask
    links:
      - timescale
  grafana:
    build:
      context: ..
      dockerfile: docker/grafana.dockerfile
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,aidanmountford-html-panel,goshposh-metaqueries-datasource,grafana-worldmap-panel,marcusolsson-gantt-panel
    container_name: grafana
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=timescale
      - POSTGRES_PASSWORD=timescale
      - POSTGRES_DB=postgres
    volumes:
      - ../timescale_data:/var/lib/postgresql/data
    container_name: videoMeshTimescaleDB