{
 "title": "1. Cluster and Node Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations o"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from cluster_details cd join organizations o on cd.organization_id = o.organization_id \nwhere o.organization_name in ('$OrganizationName')"
   },
   {
    "name": "HostName",
    "label": "Select Host Name",
    "query": "select distinct host_name from node_details nd join organizations o on nd.organization_id = o.organization_id \njoin cluster_details cd on nd.node_id = cd.node_id\nwhere o.organization_name in ('$OrganizationName') and cd.cluster_name in ($ClusterName) "
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Node Distribution based on Deployment Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select nd.deployment_type,\ncount(nd.deployment_type) as \"Value\"\nfrom node_details nd join organizations o on o.organization_id = nd.organization_id\njoin cluster_details cd on cd.node_id = nd.node_id\nwhere organization_name in ('$OrganizationName') and\ncd.cluster_name in (select cluster_name from cluster_details where cluster_name in ($ClusterName)) and \nnd.host_name in (select host_name from node_details where host_name in ($HostName))\ngroup by nd.deployment_type\n"
    }
   ]
  },
  {
   "title": "Node Location Geographical View",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 3 },
   "targets": [
    {
     "rawSql": "with t as (\n\tselect \n\t\tsplit_part(nd.timezone, '/', 1) as \"Continent\", \n\t\tsplit_part(nd.timezone, '/', 2) as \"City\",\n\t\to.organization_name,\n\t\tcd.cluster_name, \n\t\tnd.host_name \n\tfrom node_details nd join organizations o on o.organization_id = nd.organization_id \n\tjoin cluster_details cd on cd.node_id = nd.node_id\n)\n\tselect count(cc.city_name), cc.city_name, cc.latitude, cc.longitude from t join city_coordinates cc on (t.\"City\" = cc.city_name)\n\twhere \n  \t\tt.organization_name in ('$OrganizationName') and \n  \t\tt.cluster_name in ($ClusterName) and\n  \t\tt.host_name in ($HostName)\n\tgroup by cc.city_name, cc.latitude, cc.longitude"
    }
   ]
  },
  {
   "title": "Nodes Distribution across Clusters",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select cd.cluster_name, count(cd.cluster_name) as \"Value\" from cluster_details cd join organizations o on o.organization_id = cd.organization_id \njoin node_details nd on nd.node_id = cd.node_id\nwhere organization_name in ('$OrganizationName') and\ncluster_name in ($ClusterName) and\nnd.host_name in ($HostName)\ngroup by cd.cluster_name"
    }
   ]
  },
  {
   "title": "Cluster Locations based on Upgrade Timezone (if you do not see your cluster here, add it to the city_coordinates.sql file in conf)",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "rawSql": "with t as (\n\tselect \n\t\tsplit_part(cd.upgrade_schedule_timezone, '/', 1) as \"Continent\", \n\t\tsplit_part(cd.upgrade_schedule_timezone, '/', 2) as \"City\",\n\t\to.organization_name,\n\t\tcd.cluster_name, \n\t\tnd.host_name \n\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id \n\tjoin node_details nd on nd.node_id = cd.node_id\n)\n\tselect count(cc.city_name), cc.city_name, cc.latitude, cc.longitude from t join city_coordinates cc on (t.\"Continent\" = cc.continent_name and t.\"City\" = cc.city_name)\n\twhere \n  \t\tt.organization_name in ('$OrganizationName') and \n  \t\tt.cluster_name in ($ClusterName) and\n  \t\tt.host_name in ($HostName)\n\tgroup by cc.city_name, cc.latitude, cc.longitude"
    }
   ]
  },
  {
   "title": "Upgrade Schedule Days",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select \nnd.host_name,\ncase when cd.upgrade_schedule_days like ('%monday%') then true else false end as \"Monday\",\ncase when cd.upgrade_schedule_days like ('%tuesday%') then true else false end as \"Tuesday\",\ncase when cd.upgrade_schedule_days like ('%wednesday%') then true else false end as \"Wednesday\",\ncase when cd.upgrade_schedule_days like ('%thursday%') then true else false end as \"Thursday\",\ncase when cd.upgrade_schedule_days like ('%friday%') then true else false end as \"Friday\",\ncase when cd.upgrade_schedule_days like ('%saturday%') then true else false end as \"Saturday\",\ncase when cd.upgrade_schedule_days like ('%sunday%') then true else false end as \"Sunday\"\nfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\njoin node_details nd on nd.node_id = cd.node_id\nwhere \n  organization_name in ('$OrganizationName') and\n  cd.cluster_name in ($ClusterName) and\n  nd.host_name in ($HostName)"
    }
   ]
  },
  {
   "title": "Missed Upgrade",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "create or replace function count_business_days(from_date date, to_date date)\nreturns bigint\nas $fbd$\n    select count(d::date) as d\n    from generate_series(from_date, to_date, '1 day'::interval) d\n    where extract('dow' from d) not in (0, 6) \n$fbd$ language sql;\n\nselect organization_name, cd.cluster_name, nd.host_name, cd.upgrade_pending, cd.next_upgrade_time from cluster_details cd join organizations o on o.organization_id = cd.organization_id \njoin node_details nd on nd.node_id = cd.node_id\nwhere \n  organization_name in ('$OrganizationName') and\n  cluster_name in ($ClusterName) and\n  host_name in ($HostName) and\n  cd.upgrade_pending = 'true'\n  -- count_business_days(DATE(cd.next_upgrade_time), DATE(now()))  >= 2\norder by next_upgrade_time"
    }
   ]
  },
  {
   "title": "Next Upgrade Schedule",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \n  nd.host_name as \"Host name or IP\",\n  cd.next_upgrade_time as \"Next Upgrade Time\"\nfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id \njoin node_details nd on nd.node_id = cd.node_id\nwhere \n  organization_name in ('$OrganizationName') and\n  cd.cluster_name in ($ClusterName) and\n  nd.host_name in ($HostName)\norder by cd.next_upgrade_time \n"
    }
   ]
  },
  {
   "title": "Upgrade Schedule Timezone Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select cd.upgrade_schedule_timezone, count(cd.upgrade_schedule_timezone) as \"Value\" from cluster_details cd join organizations o on o.organization_id = cd.organization_id \njoin node_details nd on nd.node_id = cd.node_id\nwhere organization_name in ('$OrganizationName') and\ncd.cluster_name in ($ClusterName) and\nnd.host_name in ($HostName)\ngroup by cd.upgrade_schedule_timezone"
    }
   ]
  },
  {
   "title": "Release Channel Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 7, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select release_channel, count(cd.release_channel) as \"Value\" from cluster_details cd join organizations o on o.organization_id = cd.organization_id \njoin node_details nd on nd.node_id = cd.node_id\nwhere organization_name in ('$OrganizationName') and\ncd.cluster_name in ($ClusterName) and\nnd.host_name in ($HostName)\ngroup by cd.release_channel "
    }
   ]
  },
  {
   "title": "Distribution of Upgrade Schedule Days",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select t.\"Day\", t.\"Value\" from (\n\t(\n\t\tselect 'Monday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%monday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union \n\t(\n\t\tselect 'Tuesday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%tuesday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union\n\t(\n\t\tselect 'Wednesday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%wednesday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union\n\t(\n\t\tselect 'Thursday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%thursday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union\n\t(\n\t\tselect 'Friday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%friday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union\n\t(\n\t\tselect 'Saturday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%saturday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t) union\n\t(\n\t\tselect 'Sunday' as \"Day\",\n\t\tsum(case when cd.upgrade_schedule_days like ('%sunday%') then 1 else 0 end) as \"Value\"\n\t\tfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id\n\t\tjoin node_details nd on nd.node_id = cd.node_id\n\t\twhere organization_name in ('$OrganizationName') and\n\t\tcd.cluster_name in ($ClusterName) and\n\t\tnd.host_name in ($HostName)\n\t)\n)  t"
    }
   ]
  },
  {
   "title": "Cluster and Node Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "select cd.last_updated_timestamp as \"Last Updated Timestamp\", cd.organization_id as \"Organization ID\", cd.cluster_id as \"Cluster ID\", cd.cluster_name as \"Cluster Name\", cd.node_id as \"Node ID\", nd.host_name as \"Host Name\", nd.deployment_type as \"Deployment Type\", \nnd.country_code as \"Country Code\", nd.city as \"City\", nd.timezone as \"Timezone\", cd.release_channel as \"Release Channel\", cd.upgrade_schedule_days as \"Upgrade Schedule Days\", TO_CHAR(cd.upgrade_schedule_time, 'HH12:MI:SS') as \"Upgrade Schedule Time\", cd.upgrade_schedule_timezone as \"Upgrade Schedule Timezone\"\nfrom cluster_details cd join node_details nd on nd.node_id = cd.node_id\nwhere cd.organization_id in (select organization_id from organizations where organization_name in ('$OrganizationName')) and\ncd.cluster_name in (select cluster_name from cluster_details where cluster_name in ($ClusterName)) and\nnd.host_name in (select host_name from node_details where host_name in ($HostName))"
    }
   ]
  }
 ]
}