{
 "title": "11.1 Cluster Call Redirects",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "query": "select organization_name from organizations"
   },
   {
    "name": "OrganizationID",
    "query": "select organization_id from organizations where organization_name in ('$OrganizationName')"
   },
   {
    "name": "ClusterName",
    "query": "select distinct(c.cluster_name) from cluster_details c join webhook_events w on c.cluster_id = w.cluster_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Events Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events where $__timeFilter(webhook_events.event_timestamp) and alert_name in ('clusterCallsRedirected') and organization_id in ('$OrganizationID')"
    }
   ]
  },
  {
   "title": "Webhook Events Received Per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "$ClusterName",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "repeat": "ClusterName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events w join cluster_details c on w.cluster_id = c.cluster_id where $__timeFilter(w.event_timestamp) and w.alert_name in ('clusterCallsRedirected') and w.organization_id in ('$OrganizationID') and c.cluster_name in ($ClusterName) "
    }
   ]
  },
  {
   "title": "Call Redirect Event Distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select w.event_timestamp as \"timestamp\", c.cluster_name as \"Cluster Name\", w.metric_count as \"Call Redirects\"  from webhook_events w join cluster_details c on c.cluster_id = w.cluster_id where w.organization_id in ('$OrganizationID') GROUP BY c.cluster_name , w.event_timestamp, w.metric_count"
    }
   ]
  }
 ]
}