{
 "title": "11.2 Organization Calls Overflowed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "query": "select organization_name from organizations"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Events Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events where $__timeFilter(webhook_events.event_timestamp) and alert_name in ('orgCallsOverflowed')"
    }
   ]
  },
  {
   "title": "Events Received Per Organization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "$OrganizationName",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "repeat": "OrganizationName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events w join organizations c on w.organization_id = c.organization_id where $__timeFilter(w.event_timestamp) and w.alert_name in ('orgCallsOverflowed') and c.organization_name in ($OrganizationName)"
    }
   ]
  },
  {
   "title": "Calls Overflowed Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select w.event_timestamp as \"timestamp\", c.organization_name as \"Organization Name\", w.metric_count as \"Calls Overflowed\" from webhook_events w join organizations c on c.organization_id = w.organization_id GROUP BY c.organization_name , w.event_timestamp, w.metric_count"
    }
   ]
  }
 ]
}