{
 "title": "11. Webhooks Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "query": "select organization_name from organizations"
   },
   {
    "name": "OrganizationID",
    "query": "select organization_id from organizations where organization_name in ('$OrganizationName')"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Webhook Events Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events where $__timeFilter(webhook_events.event_timestamp) and organization_id in ('$OrganizationID')"
    }
   ]
  },
  {
   "title": "Call Overflow Events Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events where $__timeFilter(webhook_events.event_timestamp) and webhook_events.alert_name in ('orgCallsOverflowed') and organization_id in ('$OrganizationID')"
    }
   ]
  },
  {
   "title": "Cluster Call Redirected Events Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from webhook_events where $__timeFilter(webhook_events.event_timestamp) and webhook_events.alert_name in ('clusterCallsRedirected')  and organization_id in ('$OrganizationID')"
    }
   ]
  },
  {
   "title": "Historical Webhook Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp as \"Timestamp\", alert_id as \"Event ID\", organization_id as \"Organization ID\", cluster_id as \"Cluster ID\", alert_name as \"Event Name\", total_calls as \"Total Calls\", metric_count as \"Number of Calls\", absolute_percentage_over_threshold as \"Threshold Exceeded (%)\" FROM webhook_events where $__timeFilter(event_timestamp)"
    }
   ]
  }
 ]
}