{
 "title": "2. Cluster Availability",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name \nfrom cluster_details cd join organizations o on o.organization_id = cd.organization_id  \nwhere o.organization_name in ('$OrganizationName')"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Cluster Availability",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n  timestamp as \"time\", \n  cluster_name, \n  availability, \n  start_timestamp, \n  end_timestamp \nfrom cluster_availability ca join organizations o on ca.organization_id = o.organization_id\nwhere \n  organization_name in ('$OrganizationName') and \n  cluster_name in ($ClusterName) and \n  $__timeFilter(start_timestamp)"
    }
   ]
  },
  {
   "title": "Cluster Availability Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select timestamp as \"Timestamp\", organization_id as \"Organization ID\", cluster_id as \"Cluster ID\", cluster_name as \"Cluster Name\", online_nodes as \"Number of online Nodes\", offline_nodes as \"Number of offline Nodes\", availability as \"Availability\", start_timestamp as \"Segment Start Time\", end_timestamp as \"Segment End Time\" from cluster_availability ca \nwhere \n  $__timeFilter(start_timestamp) and \n  organization_id in (select organization_id from organizations where organization_name in ('$OrganizationName')) and \n  cluster_name in ($ClusterName)"
    }
   ]
  }
 ]
}