{
 "title": "3. Cluster Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from cluster_utlization cu join organizations o on o.organization_id = cu.organization_id  where organization_name in ('$OrganizationName')"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "Peak CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Peak CPU - $ClusterName",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select cu.measure_time as \"time\", cu.peak_cpu as \"Value\", cu.cluster_name from cluster_utlization cu join organizations o on o.organization_id = cu.organization_id\nwhere $__timeFilter(cu.measure_time) and\no.organization_name in ('$OrganizationName') and\ncu.cluster_name in ($ClusterName)\ngroup by cu.cluster_name, cu.measure_time, cu.peak_cpu\norder by cu.measure_time"
    }
   ]
  },
  { "title": "Average CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Average CPU - $ClusterName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select cu.measure_time as \"time\", cu.avg_cpu as \"Value\", cu.cluster_name from cluster_utlization cu join organizations o on o.organization_id = cu.organization_id\nwhere $__timeFilter(cu.measure_time) and\no.organization_name in ('$OrganizationName') and\ncu.cluster_name in ($ClusterName)\ngroup by cu.cluster_name, cu.measure_time, cu.avg_cpu\norder by cu.measure_time"
    }
   ]
  },
  { "title": "Active Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Calls - $ClusterName",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select cu.measure_time as \"time\", cu.active_calls as \"Value\", cu.cluster_name from cluster_utlization cu join organizations o on o.organization_id = cu.organization_id\nwhere $__timeFilter(cu.measure_time) and\no.organization_name in ('$OrganizationName') and\ncu.cluster_name in ($ClusterName)\ngroup by cu.cluster_name, cu.measure_time, cu.active_calls\norder by cu.measure_time"
    }
   ]
  },
  {
   "title": "Cluster Utilization Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select cu.timestamp as \"Timestamp\", cu.organization_id as \"Organization ID\", cu.measure_time as \"Response Timestamp\", cu.cluster_name as \"Cluster Name\", cu.peak_cpu as \"Peak CPU\", cu.avg_cpu as \"Average CPU\", cu.active_calls as \"Active Calls\" from cluster_utlization cu join organizations o on cu.organization_id = o.organization_id\nwhere $__timeFilter(cu.measure_time) and\no.organization_name in ('$OrganizationName') and\ncu.cluster_name in ($ClusterName)"
    }
   ]
  }
 ]
}