{
 "title": "4. Cloud Overflow",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Number of Cloud Overflows",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(co.overflow_count) from cloud_overflow co join organizations o on o.organization_id = co.organization_id\nwhere $__timeFilter(co.overflow_time) and o.organization_name in ('$OrganizationName')"
    }
   ]
  },
  {
   "title": "Distribution of Cloud Overflow Counts Reasons",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select sum(co.overflow_count), co.reason \nfrom cloud_overflow co join organizations o on o.organization_id = co.organization_id \nwhere $__timeFilter(co.overflow_time) and o.organization_name in ('$OrganizationName')\ngroup by reason "
    }
   ]
  },
  { "title": "Cloud Overflow Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cloud Overflows - $OrganizationName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "repeat": "OrganizationName",
   "targets": [
    {
     "rawSql": "select co.overflow_time  as \"time\", co.overflow_count as \"Value\", co.reason\nfrom cloud_overflow co join organizations o on o.organization_id = co.organization_id \nwhere $__timeFilter(co.overflow_time) and o.organization_name in ('$OrganizationName')\ngroup by co.overflow_time, co.overflow_count, co.reason"
    }
   ]
  },
  { "title": "Cloud Overflow Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cloud Overflow Details - $OrganizationName",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "repeat": "OrganizationName",
   "targets": [
    {
     "rawSql": "select o.organization_id as \"Organization ID\", overflow_time as \"Overflow Time\", overflow_count as \"Overflow Count\", reason as \"Reason\", remediation as \"Remediation\" from cloud_overflow co join organizations o on o.organization_id = co.organization_id \nwhere $__timeFilter(co.overflow_time) and o.organization_name in ('$OrganizationName')"
    }
   ]
  }
 ]
}