{
 "title": "5. Call Redirects",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from call_redirects ca join organizations o on o.organization_id = ca.organization_id  where organization_name in ('$OrganizationName')"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Number of Call Redirects - $ClusterName",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(cr.redirect_count) from call_redirects cr join organizations o on cr.organization_id = o.organization_id\nwhere $__timeFilter(cr.redirect_time) and o.organization_name in ('$OrganizationName') and cr.cluster_name in ($ClusterName)"
    }
   ]
  },
  {
   "title": "Call Redirect Counts by Cluster",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 3 },
   "targets": [
    {
     "rawSql": "select sum(cr.redirect_count), cr.cluster_name from call_redirects cr join organizations o on o.organization_id = cr.organization_id\nwhere $__timeFilter(cr.redirect_time) and o.organization_name in ('$OrganizationName') and cr.cluster_name in ($ClusterName)\ngroup by cluster_name"
    }
   ]
  },
  {
   "title": "Distribution of Call Redirect Counts Reasons",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(cr.redirect_count), cr.reason from call_redirects cr join organizations o on cr.organization_id = o.organization_id\nwhere $__timeFilter(cr.redirect_time) and o.organization_name in ('$OrganizationName') and cr.cluster_name in ($ClusterName)\ngroup by cr.reason "
    }
   ]
  },
  {
   "title": "Call Redirects Trend per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Number of Call Redirects - $ClusterName",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 15 },
   "repeat": "ClusterName",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select redirect_time as \"time\", redirect_count as \"Value\", reason from call_redirects cr join organizations o on cr.organization_id = o.organization_id\nwhere $__timeFilter(redirect_time) and cluster_name in ($ClusterName)\ngroup by redirect_time, redirect_count, reason\norder by time"
    }
   ]
  },
  { "title": "Call Redirects Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Call Redirects Details - $OrganizationName",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select o.organization_name as \"Organization Name\", cr.cluster_name as \"Cluster Name\", cr.redirect_time as \"Redirect Time\", cr.redirect_count as \"Redirect Count\", cr.reason as \"Reason\", cr.remediation as \"Remediation\"\nfrom call_redirects cr join organizations o on o.organization_id = cr.organization_id\nwhere o.organization_name in ('$OrganizationName') and cr.cluster_name in ($ClusterName)"
    }
   ]
  }
 ]
}