{
 "title": "6. Node Availability",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from node_availability na join organizations o \non o.organization_id = na.organization_id \nwhere organization_name in ('$OrganizationName')"
   },
   {
    "name": "HostName",
    "label": "Select Host Name",
    "query": "select distinct host_name from node_availability na join organizations o\non o.organization_id = na.organization_id \nwhere cluster_name in ($ClusterName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Node Availability",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n  timestamp as \"time\", \n  host_name, \n  availability, \n  segment_start_time, \n  segment_end_time \nfrom node_availability na join organizations o on na.organization_id = o.organization_id\nwhere \n  $__timeFilter(segment_start_time) and\n  o.organization_name in ('$OrganizationName') and \n  cluster_name in ($ClusterName) and \n  host_name in ($HostName)"
    }
   ]
  },
  {
   "title": "Node Availability Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "select timestamp as \"Timestamp\", organization_id as \"Organization ID\", cluster_id as \"Cluster ID\", cluster_name as \"Cluster Name\", node_id as \"Node ID\", host_name as \"Host Name\", availability as \"Availability\", segment_start_time as \"Segment Start Time\", segment_end_time as \"Segment End Time\" from node_availability na \nwhere \n  $__timeFilter(segment_start_time) and \n  organization_id in (select organization_id from organizations where organization_name in ('$OrganizationName')) and\n  cluster_name in ($ClusterName) and\n  host_name in ($HostName)"
    }
   ]
  }
 ]
}