{
 "title": "7. Media Health Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from media_health_monitoring_tool mhmt join organizations o \non o.organization_id = mhmt.organization_id \nwhere organization_name in ('$OrganizationName')"
   },
   {
    "name": "HostName",
    "label": "Select Host Name",
    "query": "select distinct host_name from media_health_monitoring_tool mhmt join organizations o \non o.organization_id = mhmt.organization_id \nwhere cluster_name in ($ClusterName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "SIP Signalling Distribution - Overall",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt join organizations o on o.organization_id = mhmt.organization_id\nwhere test_name = 'SIP Signalling' and $__timeFilter(test_time) and test_result = 'Success' and organization_name in ('$OrganizationName') and cluster_name in ($ClusterName) and host_name in ($HostName)"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt join organizations o on o.organization_id = mhmt.organization_id\nwhere failure_reason is NOT NULL and test_name = 'SIP Signalling' and $__timeFilter(test_time) and test_result = 'Failed' and organization_name in ('$OrganizationName')  and cluster_name in ($ClusterName) and host_name in ($HostName)\ngroup by failure_reason"
    }
   ]
  },
  {
   "title": "Media Cascade Distribution - Overall",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt join organizations o on mhmt.organization_id = o.organization_id\nwhere test_name = 'Media Cascade' and $__timeFilter(test_time) and test_result = 'Success' and organization_name in ('$OrganizationName') and cluster_name in ($ClusterName) and host_name in ($HostName)"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt join organizations o on mhmt.organization_id = o.organization_id\nwhere failure_reason is NOT NULL and test_name = 'Media Cascade' and $__timeFilter(test_time) and test_result = 'Failed' and organization_name in ('$OrganizationName') and cluster_name in ($ClusterName) and host_name in ($HostName)\ngroup by failure_reason"
    }
   ]
  },
  {
   "title": "Media Singalling Distribution - Overall",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt join organizations o on mhmt.organization_id = o.organization_id\nwhere test_name = 'Media Signalling' and $__timeFilter(test_time) and test_result = 'Success' and organization_name in ('$OrganizationName')  and cluster_name in ($ClusterName) and host_name in ($HostName)"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt join organizations o on mhmt.organization_id = o.organization_id\nwhere failure_reason is NOT NULL and test_name = 'Media Signalling' and $__timeFilter(test_time) and test_result = 'Failed' and organization_name in ('$OrganizationName')  and cluster_name in ($ClusterName) and host_name in ($HostName)\ngroup by failure_reason"
    }
   ]
  },
  { "title": "SIP Signalling - Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "SIP Signalling Distribution - $HostName",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 20 },
   "repeat": "HostName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'SIP Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Success'"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt \nwhere test_name = 'SIP Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Failed'\ngroup by failure_reason"
    }
   ]
  },
  { "title": "SIP Signalling Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "SIP Signalling Trend - $HostName",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 45 },
   "repeat": "HostName",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nCASE WHEN test_result = 'Success' THEN 1 end as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'SIP Signalling' and host_name in ($HostName) and $__timeFilter(test_time)\norder by test_time"
    },
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nfailure_reason,\nCASE WHEN test_result = 'Failed' THEN 0 end as \"Value\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'SIP Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Failed'\norder by test_time"
    }
   ]
  },
  { "title": "Media Cascade - Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Media Cascade Distribution - $HostName",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 68 },
   "repeat": "HostName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Cascade' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Success'"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt \nwhere failure_reason is NOT NULL and test_name = 'Media Cascade' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Failed'\ngroup by failure_reason"
    }
   ]
  },
  { "title": "Media Cascade Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Media Cascade Trend - $HostName",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 93 },
   "repeat": "HostName",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nCASE WHEN test_result = 'Success' THEN 1 end as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Cascade' and host_name in ($HostName) and $__timeFilter(test_time)\norder by test_time"
    },
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nfailure_reason,\nCASE WHEN test_result = 'Failed' THEN 0 end as \"Value\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Cascade' and host_name in ($HostName) and $__timeFilter(test_time) and test_result='Failed'\norder by test_time"
    }
   ]
  },
  {
   "title": "Media Signalling - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }
  },
  {
   "title": "Media Signalling Distribution - $HostName",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 116 },
   "repeat": "HostName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOUNT(*) as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Success'"
    },
    {
     "rawSql": "select count(failure_reason), failure_reason as \"Value\" from media_health_monitoring_tool mhmt \nwhere failure_reason is NOT NULL and test_name = 'Media Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Failed'\ngroup by failure_reason"
    }
   ]
  },
  { "title": "Media Signalling Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Media Signalling Trend - $HostName",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 141 },
   "repeat": "HostName",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nCASE WHEN test_result = 'Success' THEN 1 end as \"Success\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Signalling' and host_name in ($HostName) and $__timeFilter(test_time)\norder by test_time"
    },
    {
     "rawSql": "SELECT \ntest_time as \"time\", \nfailure_reason,\nCASE WHEN test_result = 'Failed' THEN 0 end as \"Value\"\nfrom media_health_monitoring_tool mhmt \nwhere test_name = 'Media Signalling' and host_name in ($HostName) and $__timeFilter(test_time) and test_result = 'Failed'\norder by test_time"
    }
   ]
  },
  {
   "title": "Media Health Monitoring Tool Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 }
  },
  {
   "title": "Media Health Monitoring Tool Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {
     "rawSql": "select timestamp as \"Timestamp\", organization_id as \"Organization ID\", cluster_id as \"Cluster ID\", cluster_name as \"Cluster Name\", node_id as \"Node ID\", host_name as \"Host Name\", test_time as \"Test Time\", test_name as \"Test Name\", test_result as \"Test Result\", failure_reason as \"Failure Reason\" from media_health_monitoring_tool where $__timeFilter(test_time) and host_name in ($HostName)"
    }
   ]
  }
 ]
}