{
 "title": "8. Reachability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Select Organization Name",
    "query": "select distinct organization_name from organizations"
   },
   {
    "name": "ClusterName",
    "label": "Select Cluster Name",
    "query": "select distinct cluster_name from reachability r  join organizations o \non o.organization_id = r.organization_id \nwhere organization_name in ('$OrganizationName')"
   },
   {
    "name": "HostName",
    "label": "Select Host Name",
    "query": "select distinct host_name from reachability r join organizations o \non o.organization_id = r.organization_id \nwhere cluster_name in ($ClusterName)"
   },
   {
    "name": "DestinationCluster",
    "label": "Select Destination Cluster",
    "query": "select distinct destination_cluster from reachability r"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ${OrganizationName} </center></h1>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "UDP Destination Cluster Reachability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "UDP Reachability from $ClusterName",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "repeat": "ClusterName",
   "targets": [
    {
     "rawSql": "select  \n\tdestination_cluster as \"Destination Cluster\", \n\tcase \n\t\twhen ((count(case when reachability = 'true' then 1 else null end) * 100) / count(*)) >= 90 then 2\n\t\twhen (count(case when reachability = 'false' then 1 else null end) = count(*)) then 0\n\t\telse 1\n\tend as \"Reachability\"\nfrom \n(\n\tSELECT r2.cluster_id, r2.cluster_name, r2.destination_cluster, r2.reachability, r2.reachability_type \n\tfrom reachability r2 JOIN organizations o on r2.organization_id  = o.organization_id \n\twhere \n\t\to.organization_name  IN ('$OrganizationName') and\n\t\tr2.cluster_name in ($ClusterName) and\n\t\t$__timeFilter(r2.test_time) and\n\t\tr2.host_name in ($HostName) and\n\t\tr2.reachability_type='udp'\n\torder by r2.destination_cluster \n) t\ngroup by destination_cluster \norder by \"Reachability\" asc"
    }
   ]
  },
  {
   "title": "TCP Destination Cluster Reachability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "TCP Reachability from $ClusterName",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "repeat": "ClusterName",
   "targets": [
    {
     "rawSql": "select  \n\tdestination_cluster as \"Destination Cluster\", \n\tcase \n\t\twhen ((count(case when reachability = 'true' then 1 else null end) * 100) / count(*)) >= 90 then 2\n\t\twhen (count(case when reachability = 'false' then 1 else null end) = count(*)) then 0\n\t\telse 1\n\tend as \"Reachability\"\nfrom \n(\n\tSELECT r2.cluster_id, r2.cluster_name, r2.destination_cluster, r2.reachability, r2.reachability_type \n\tfrom reachability r2 JOIN organizations o on r2.organization_id  = o.organization_id \n\twhere \n\t\to.organization_name  IN ('$OrganizationName') and\n\t\tr2.cluster_name in ($ClusterName) and\n\t\t$__timeFilter(r2.test_time) and\n\t\tr2.host_name in ($HostName) and\n\t\tr2.reachability_type='tcp'\n\torder by r2.destination_cluster \n) t\ngroup by destination_cluster \norder by \"Reachability\" asc"
    }
   ]
  },
  { "title": "UDP Reachable Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "UDP Reachable Ports [50000-53000]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='true' and \n  \t\tr.reachability_type = 'udp' and\n  \t\tr.port > 50000 and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='true' and \n  r.reachability_type = 'udp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  {
   "title": "UDP Not Reachable Ports [50000-53000]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='false' and \n  \t\tr.reachability_type = 'udp' and\n  \t\tr.port > 50000 and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='false' and \n  r.reachability_type = 'udp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  {
   "title": "UDP Reachable Port [5004]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='true' and \n  \t\tr.reachability_type = 'udp' and\n  \t\tr.port = 5004 and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='true' and \n  r.reachability_type = 'udp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  {
   "title": "UDP Not Reachable Port [5004]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='false' and \n  \t\tr.reachability_type = 'udp' and\n  \t\tr.port = 5004 and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='false' and \n  r.reachability_type = 'udp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  { "title": "TCP Reachable Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "TCP Reachable Ports",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='true' and \n  \t\tr.reachability_type = 'tcp' and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='true' and \n  r.reachability_type = 'tcp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  {
   "title": "TCP Not Reachable Ports",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  r.test_time as \"time\",\n  r.port as \"Port\"\nFROM reachability r join organizations o on r.organization_id = o.organization_id\nWHERE \n  r.port in (\n  \tSELECT distinct port from reachability r join organizations o on r.organization_id = o.organization_id\n  \twhere \n  \t\to.organization_name in ('$OrganizationName') and \n  \t\tr.cluster_name in ($ClusterName) and \n  \t\tr.host_name in ($HostName) and \n  \t\tr.reachability='false' and \n  \t\tr.reachability_type = 'tcp' and\n  \t\t$__timeFilter(test_time)\n  ) and\n  $__timeFilter(test_time) and\n  o.organization_name IN ('$OrganizationName') and\n  r.cluster_name IN ($ClusterName) and\n  r.destination_cluster IN ($DestinationCluster) and\n  r.host_name IN ($HostName) and \n  r.reachability='false' and \n  r.reachability_type = 'tcp'\ngroup by r.port, r.test_time\norder by \"time\""
    }
   ]
  },
  { "title": "UDP Reachability Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "UDP Reachability",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "rawSql": "select r.timestamp, r.from_time, r.to_time, o.organization_name, r.cluster_name, r.host_name, r.destination_cluster, r.test_time, r.reachability_type, r.port, r.reachability\nfrom reachability r join organizations o on r.organization_id = o.organization_id\nwhere o.organization_name in ('$OrganizationName') and r.cluster_name in ($ClusterName) and r.host_name in ($HostName) and r.reachability_type='udp' and $__timeFilter(r.test_time)"
    }
   ]
  },
  { "title": "TCP Reachability Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "TCP Reachability",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "rawSql": "select r.timestamp, r.from_time, r.to_time, o.organization_name, r.cluster_name, r.host_name, r.destination_cluster, r.test_time, r.reachability_type, r.port, r.reachability\nfrom reachability r join organizations o on r.organization_id = o.organization_id\nwhere o.organization_name in ('$OrganizationName') and r.cluster_name in ($ClusterName) and r.host_name in ($HostName) and r.reachability_type='tcp' and $__timeFilter(r.test_time)"
    }
   ]
  }
 ]
}